spring:
  application:
    name: cloud-client1

server:
  port: 8882
  servlet:
    context: /cloud-client1

welcome:
  hello: hello-dev-aroundx

management:
  endpoints:
    web:
      exposure:
        include: "*"